# Generated by Django 3.0.3 on 2020-02-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=250)),
                ('fechaIngreso', models.CharField(max_length=250)),
                ('fechaCaducidad', models.CharField(max_length=250)),
                ('cantidad', models.CharField(max_length=250)),
                ('ventasPieza', models.CharField(max_length=250)),
            ],
        ),
    ]
