# Generated by Django 3.0.3 on 2020-02-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
