# Generated by Django 3.0.3 on 2020-02-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_auto_20200213_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=254),
        ),
    ]
